apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ubereats-prototype-frontend:latest    #ubereats-prototype-frontend:latest  # Use your frontend image name
          ports:
            - containerPort: 3000
          imagePullPolicy: IfNotPresent
